version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "vaccination-reservation"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bwdpvkgqwmj2"
s3_prefix = "vaccination-reservation"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DDBTableName=\"VACCINATION_RESERVATION\""
image_repositories = []
